---
- hosts: elevate
  vars:
    project_path: /opt/frontend/observation-portal
    root_path: /opt/frontend
  tasks:
    - name: Slurp host file
      slurp:
        src: "/opt/backend/deployment/.token"
      register: slurpfile

    - name: Run vault credentials
      shell: "curl --location --request GET '{{ vaultAddress }}mentored-portal' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{root_path}}/data-observation.json'"
      register: vaultCurl

    - name: Show Vault environment data
      shell: cat {{root_path}}/data2.json | jq '.data'
      register: vaultEnvData

    - name: Print Vault environment data
      debug:
        msg: "{{ vaultEnvData.stdout }}"

    - name: Ensure project directory exists
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: Clone observation-portal repo
      git:
        # repo: https://github.com/ELEVATE-Project/observation-portal
        repo: https://github.com/farhanp1502/observation-portal
        dest: "{{project_path}}"
        version: "{{gitBranch}}"
        force: yes

    - name: Install dependencies
      shell: cd {{project_path}} && npm i --force

    - name: Set permission for env script
      shell: chmod 744 {{ project_path }}/src/scripts/json2env.sh

    # - name: Generate environment.ts
    #   shell: |
    #     cat {{root_path}}/data2.json | jq '.data' > {{ project_path }}/src/assets/environments/environment.ts &&
    #     sed -i '1s/^/export const environment = \n/' {{ project_path }}/src/assets/environments/environment.ts
    #   register: envConfig

    - name: Convert JSON to window["env"] format and store in environment.ts
      shell: cat {{ root_path }}/data2.json | {{ project_path }}/src/scripts/json2env.sh > {{ project_path }}/.env
      register: envConfig

    # - debug: msg="envConfig result: {{ envConfig }}"

    - name: Fetch pm2 config file
      shell: "curl --location --request GET '{{ vaultAddress }}observationPortalPm2Config' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data.data' > '{{ project_path }}/pm2.config.json'"
      register: pm2

    - name: Remove old build folder
      shell: rm -rf {{project_path}}/dist

    - name: Build Angular app
      shell: cd {{project_path}} && ng build --configuration production

    - name: Start pm2 with config
      shell: cd {{project_path}} && pm2 start pm2.config.json
